ftp:
    host: 123.0.0.0
    # 21 is the default FTP port, you can probably leave it as is, unless otherwise stated.
    port: 21
    username: admin
    password: password123
    folder: /
sync-files:
- /plugins/Installer/SYNC_DEFAULT
- /plugins/Installer/SYNC_TEST